### ISSUE TITLE
Кривая генерация гробниц

### ISSUE THREAD

**Issue by 6oogle** [DelfikPro/Implario#1]
Сид: 5205451494202728313
Координаты: 75, 75, 250

![DhhiZHT](https://user-images.githubusercontent.com/33707322/61061270-98175080-a404-11e9-9fef-695f59dbf05f.png)

**Comment by DelfikPro** [comment]
Исправлено.
![FHkuQFLJy0E](https://user-images.githubusercontent.com/33707322/61582503-70c33080-ab34-11e9-92d7-308845ca4d81.jpg)

**Comment by TheLegionCrazy** [comment]
нормальная генерация, че ты

**Comment by DelfikPro** [comment]
Исправлено в коммите 1c8719e0d8ad12d98dc4e82b1aa46cad46a6cb79

![image](https://user-images.githubusercontent.com/33707322/62013843-4ced9380-b1a1-11e9-9a24-212a175ff3d3.png)
