### ISSUE TITLE
Странно выглядит трава

### ISSUE THREAD

**Issue by 6oogle** [DelfikPro/Implario#10]
Ну трава выглядит очень странно

Инструкция для воспроизведения :
1. Зайдите в мир
2. Посмотрите на траву
3. 
![image](https://user-images.githubusercontent.com/32604831/62013984-b40c4780-b1a3-11e9-93f6-16cf12e888ca.png)
![image](https://user-images.githubusercontent.com/32604831/62013987-b8d0fb80-b1a3-11e9-9ec8-8acfba606128.png)

**Comment by DelfikPro** [comment]
Исправлено коммитом 03f25badbb1e1b050a298f8b121aa841aeefed3a
