### ISSUE TITLE
Странно работают рельсы

### ISSUE THREAD

**Issue by 6oogle** [DelfikPro/Implario#15]
![image](https://user-images.githubusercontent.com/32604831/62430163-2d1a1a80-b721-11e9-9d45-33273a492088.png)

**Comment by DelfikPro** [comment]
**Intended behaviour**
Такая конструкция образует односторонний проезд для вагонеток. Когда вагонетка спускается вниз по таким рельсам, она не теряет свою скорость. Это позволяет делать очень быстрые лифты вниз.


![15](https://user-images.githubusercontent.com/33707322/62444263-b6534080-b765-11e9-8c88-6a0c4fa55ef8.gif)
