### ISSUE TITLE
Кривой рендер стеклянных панелей

### ISSUE THREAD

**Issue by 6oogle** [DelfikPro/Implario#16]
![image](https://user-images.githubusercontent.com/32604831/62430203-e5e05980-b721-11e9-9e82-9a449b7fe05d.png)
![image](https://user-images.githubusercontent.com/32604831/62430209-00b2ce00-b722-11e9-97f3-71edd44c0619.png)
![image](https://user-images.githubusercontent.com/32604831/62430212-0f00ea00-b722-11e9-8044-006b78750d80.png)

**Comment by DelfikPro** [comment]
Баг нотчиана. 

Когда сверху панели стоит другая панель, верхняя сторона первой не рендерится (как и нижняя сторона верхней панели)

**Comment by DelfikPro** [comment]
#### WAI
Работает по задумке. Фикс будет слишком выпирающим и нагружающим костылём.
