### ISSUE TITLE
Тёмная грядка

### ISSUE THREAD

**Issue by 6oogle** [DelfikPro/Implario#2]
Тёмная грядка

![image](https://user-images.githubusercontent.com/32604831/61063282-62746680-a408-11e9-8408-20ad1cba1644.png)

**Comment by 6oogle** [comment]
Не хорошо

![image](https://user-images.githubusercontent.com/32604831/61243879-95449480-a751-11e9-825b-a7316de9b7be.png)

**Comment by DelfikPro** [comment]
Исправлено с помощью #6.
